services:
  web:
    image: mab:2.0
    build:
      target: web
      context: .
    env_file:
      - .env
    ports:
      - "8091:80"
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    develop:
      watch:
        - action: sync
          path: .
          target: /var/www/html

networks:
  app-network:
