services:
    web:
        image: mab:2.0
        build:
            context: .
        env_file:
            - .env
        ports:
            - "8091:80"
        read_only: false # Permite que el sistema operativo escriba en tmpfs interno
        tmpfs:
            - /tmp:exec,mode=1777  # Aísla la carpeta /tmp en RAM
            - /var/tmp:exec,mode=1777
        volumes:
            # El código fuente se monta como SOLO LECTURA (:ro)
            - .:/var/www/html:ro
            # Solo las carpetas que requieren escritura quedan en :rw
            - ./storage:/var/www/html/storage:rw
            - ./bootstrap/cache:/var/www/html/bootstrap/cache:rw
            - vendor:/var/www/html/vendor
            - node_modules:/var/www/html/node_modules
            - build:/var/www/html/public/build
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost/health"]
            start_period: 30s
            retries: 10
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    vendor:
    node_modules:
    build:
