services:
    web:
        image: mab:2.0
        build:
            context: .
        env_file:
            - .env
        ports:
            - "8091:80"
        volumes:
            - .:/var/www/html
            - vendor:/var/www/html/vendor
            - node_modules:/var/www/html/node_modules
            - build:/var/www/html/public/build
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost/health"]
            start_period: 30s
            retries: 10
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    vendor:
    node_modules:
    build:
